# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  test-infra:
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          apk add build-base
          curl -o go.tar.gz https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
          tar -C /usr/local -xzf go.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go get github.com/gruntwork-io/terratest/modules/terraform
          export GOOGLE_CLOUD_KEYFILE_JSON=~/.config/gcloud/legacy_credentials/terraform-test@nifi-staq-test.iam.gserviceaccount.com/adc.json # Not sure why?
          go test
  deploy-infra:
    environment:
      TERRAFORM_COMMAND: apply
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - test-infra
      - deploy-infra:
          requires:
          - test-infra

