version: 2
jobs:
  test-infra:
    docker:
      - image: sleyva97/terraform:0.0.1
    environment:
      TF_VAR_TERRAFORM_STATE_BUCKET: staq-terraform-state
      TF_VAR_ENVIRONMENT: test
    steps:
      - checkout
      - run : |
          entrypoint || true # For creds
          apk add build-base
          curl -o go.tar.gz https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
          tar -C /usr/local -xzf go.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go get github.com/gruntwork-io/terratest/modules/terraform
          export GOOGLE_CLOUD_KEYFILE_JSON="$HOME/.config/gcloud/legacy_credentials/terraform-test@nifi-staq-test.iam.gserviceaccount.com/adc.json"
          export TF_VAR_GOOGLE_CLOUD_KEYFILE_JSON=$GOOGLE_CLOUD_KEYFILE_JSON
          go test
  deploy-staging:
    environment:
      TERRAFORM_COMMAND: apply
      TF_VAR_TERRAFORM_STATE_BUCKET: staq-terraform-state
      TF_VAR_ENVIRONMENT: staging
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - test-infra
      - deploy-staging:
          requires:
          - test-infra

